#ifndef CONSTANTES_H
#define CONSTANTES_H

#define WATTS_POR_METRO_QUADRADO_TIPO_0 12
#define WATTS_POR_METRO_QUADRADO_TIPO_1 15
#define WATTS_POR_METRO_QUADRADO_TIPO_2 18
#define WATTS_POR_METRO_QUADRADO_TIPO_3 20
#define WATTS_POR_METRO_QUADRADO_TIPO_4 22

#define POTENCIA_LAMPADA 60

#endif